runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 6
  memory_gb: 12
  disk_size_gb: 15

api_version: 1.0.5

handlers:
- url: /search/.*
  script: auto