NO_ABOVE = 0.5
NO_BELOW = 5
NUM_SEARCH_RESULTS_TAKE = 10
NUM_TOPICS = 10000
DATA_PATH = 'data'
DATASET_NAME = '20newsgroups'
CORE_PATH = (DATA_PATH, DATASET_NAME)
LSI_MODEL_PATH: str = '%s/%s.lsi' % CORE_PATH
CORPUS_PATH = '%s/%s.mm' % CORE_PATH
NEWSGROUP_DICT_PATH = '%s/%s.dict' % CORE_PATH
TFID_MODEL_PATH = '%s/%s.tfid' % CORE_PATH
INDEX_PATH = '%s/%s.index' % CORE_PATH
REMOVE_FROM_TRAIN_DATA = ('headers', 'footers', 'quotes')
QUERY_ARG = "--query"
DEBUG_ARG = "--debug"
HOST_ARG = "--host"
PORT_ARG = "--port"
DEFAULT_PORT = 5000
DEFAULT_HOST = '0.0.0.0'
